name: socksproxyserver
authors:
  - name: Anthony Rose
    handle: '@Cx01N'
    link: https://twitter.com/Cx01N_
  - name:
    handle: '@mjokic'
    link:
software:
techniques: []
main: socksproxyserver.py
